import type { MachineProfile, Settings } from './types';
import { transformedBounds } from './transform';
export const profiles: MachineProfile[] = [
 {id:'cnc',name:'Generic CNC Router',kind:'cnc',header:'G90\nG17',footer:'M2',toolOn:'',toolOff:'',safeZ:5,workZ:-1,passDepth:1,feed:600,travel:1800},
 {id:'pen',name:'Generic Pen Plotter',kind:'pen',header:'G90',footer:'M2',toolOn:'',toolOff:'',safeZ:5,workZ:0,passDepth:1,feed:1500,travel:3000},
 {id:'laser',name:'Generic XY Laser-Style',kind:'laser',header:'G90',footer:'M2',toolOn:'',toolOff:'',safeZ:0,workZ:0,passDepth:1,feed:1200,travel:3000}
];
export const defaults: Settings = { units:'mm',workWidth:300,workHeight:200,outputWidth:150,outputHeight:100,lockAspect:true,offsetX:0,offsetY:0,rotationDeg:0,origin:'bottom-left',invertX:false,invertY:false,feed:600,travel:1800,safeZ:5,workZ:-1,maxDepth:-2,passes:1,lineSpacing:0.5,precision:3,threshold:128,serpentine:true,simplify:1,toolpathDetail:.3,previewQuality:'balanced',brightness:0,contrast:0,invert:false,filter:'grayscale',fit:true };
export const loadSettings=():Settings=>{try{const saved=JSON.parse(localStorage.getItem('i2g-settings')||'{}');const toolpathDetail=Number(saved.toolpathDetail);const rotationDeg=Number(saved.rotationDeg);const previewQuality=['low','balanced','high','full'].includes(saved.previewQuality)?saved.previewQuality:defaults.previewQuality;return{...defaults,...saved,rotationDeg:Number.isFinite(rotationDeg)?rotationDeg:defaults.rotationDeg,toolpathDetail:Number.isFinite(toolpathDetail)&&toolpathDetail>=.05?toolpathDetail:defaults.toolpathDetail,previewQuality}}catch{return{...defaults}}};
export const loadProfiles=():MachineProfile[]=>{try{return [...profiles,...JSON.parse(localStorage.getItem('i2g-profiles')||'[]')]}catch{return profiles}};
export function validate(s:Settings){const w:string[]=[];const numeric=[s.workWidth,s.workHeight,s.outputWidth,s.outputHeight,s.offsetX,s.offsetY,s.rotationDeg,s.feed,s.travel,s.safeZ,s.workZ,s.maxDepth,s.passes,s.lineSpacing,s.precision,s.threshold,s.simplify,s.toolpathDetail];if(numeric.some(value=>!Number.isFinite(value)))w.push('Configuration contains a malformed numeric value.'); if(s.workWidth<=0||s.workHeight<=0||s.outputWidth<=0||s.outputHeight<=0)w.push('Dimensions must be greater than zero.'); if(s.feed<=0||s.travel<=0)w.push('Feed rates must be positive.'); if(s.safeZ<0)w.push('Safe Z should not be negative.'); if(s.workZ>s.safeZ||s.maxDepth>s.safeZ)w.push('Working Z values must be below safe Z.'); if(s.passes<1||!Number.isInteger(s.passes))w.push('Pass count must be a positive integer.'); if(s.lineSpacing<=0)w.push('Line spacing must be positive.'); if(s.toolpathDetail<.05||s.toolpathDetail>5)w.push('Toolpath detail must be between 0.05 mm and 5 mm.'); if(s.precision<0||s.precision>8||!Number.isInteger(s.precision))w.push('Precision must be an integer from 0 to 8.'); const bounds=transformedBounds(s);if(bounds.minX<0||bounds.minY<0||bounds.maxX>s.workWidth||bounds.maxY>s.workHeight)w.push('Transformed image exceeds the configured work area.'); return w;}
