import type { MachineProfile, Settings } from './types';
import { transformedBounds } from './transform';
export const profiles: MachineProfile[] = [
 {id:'cnc',name:'Generic CNC Router',kind:'cnc',header:'G90\nG17',footer:'M2',toolOn:'',toolOff:'',safeZ:5,workZ:-1,passDepth:1,feed:600,travel:1800},
 {id:'pen',name:'Generic Pen Plotter',kind:'pen',header:'G90',footer:'M2',toolOn:'',toolOff:'',safeZ:5,workZ:0,passDepth:1,feed:1500,travel:3000},
 {id:'laser',name:'Generic XY Laser-Style',kind:'laser',header:'G90',footer:'M2',toolOn:'',toolOff:'',safeZ:0,workZ:0,passDepth:1,feed:1200,travel:3000}
];
export const defaults: Settings = { units:'mm',workWidth:300,workHeight:200,outputWidth:150,outputHeight:100,lockAspect:true,offsetX:0,offsetY:0,rotationDeg:0,origin:'bottom-left',invertX:false,invertY:false,feed:600,travel:1800,safeZ:5,workZ:-1,maxDepth:-2,passes:1,lineSpacing:0.5,precision:3,threshold:128,serpentine:true,simplify:1,toolpathDetail:.3,previewQuality:'balanced',brightness:0,contrast:0,invert:false,filter:'grayscale',fit:true };
const record = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const finite = (value: unknown, fallback: number) => typeof value === 'number' && Number.isFinite(value) ? value : fallback;
const flag = (value: unknown, fallback: boolean) => typeof value === 'boolean' ? value : fallback;
const text = (value: unknown, fallback: string, maximum = 16_384) => typeof value === 'string' ? value.slice(0, maximum) : fallback;
const oneOf = <T extends string>(value: unknown, values: readonly T[], fallback: T): T => typeof value === 'string' && values.includes(value as T) ? value as T : fallback;

/** localStorage is untrusted input: reconstruct only the known settings schema. */
export const loadSettings=():Settings=>{try{const parsed:unknown=JSON.parse(localStorage.getItem('i2g-settings')||'{}');if(!record(parsed))return{...defaults};return{units:oneOf(parsed.units,['mm','in'],defaults.units),workWidth:finite(parsed.workWidth,defaults.workWidth),workHeight:finite(parsed.workHeight,defaults.workHeight),outputWidth:finite(parsed.outputWidth,defaults.outputWidth),outputHeight:finite(parsed.outputHeight,defaults.outputHeight),lockAspect:flag(parsed.lockAspect,defaults.lockAspect),offsetX:finite(parsed.offsetX,defaults.offsetX),offsetY:finite(parsed.offsetY,defaults.offsetY),rotationDeg:finite(parsed.rotationDeg,defaults.rotationDeg),origin:oneOf(parsed.origin,['bottom-left','top-left','center'],defaults.origin),invertX:flag(parsed.invertX,defaults.invertX),invertY:flag(parsed.invertY,defaults.invertY),feed:finite(parsed.feed,defaults.feed),travel:finite(parsed.travel,defaults.travel),safeZ:finite(parsed.safeZ,defaults.safeZ),workZ:finite(parsed.workZ,defaults.workZ),maxDepth:finite(parsed.maxDepth,defaults.maxDepth),passes:finite(parsed.passes,defaults.passes),lineSpacing:finite(parsed.lineSpacing,defaults.lineSpacing),precision:finite(parsed.precision,defaults.precision),threshold:finite(parsed.threshold,defaults.threshold),serpentine:flag(parsed.serpentine,defaults.serpentine),simplify:finite(parsed.simplify,defaults.simplify),toolpathDetail:finite(parsed.toolpathDetail,defaults.toolpathDetail),previewQuality:oneOf(parsed.previewQuality,['low','balanced','high','full'],defaults.previewQuality),brightness:finite(parsed.brightness,defaults.brightness),contrast:finite(parsed.contrast,defaults.contrast),invert:flag(parsed.invert,defaults.invert),filter:oneOf(parsed.filter,['grayscale','threshold','edge','dither'],defaults.filter),fit:flag(parsed.fit,defaults.fit)}}catch{return{...defaults}}};
const safeProfile=(value:unknown):MachineProfile|null=>{if(!record(value))return null;const kind=value.kind==='cnc'||value.kind==='pen'||value.kind==='laser'?value.kind:null;if(!kind)return null;const id=text(value.id,'',128);const name=text(value.name,'',128);if(!id||!name)return null;return{id,name,kind,header:text(value.header,''),footer:text(value.footer,''),toolOn:text(value.toolOn,''),toolOff:text(value.toolOff,''),safeZ:finite(value.safeZ,0),workZ:finite(value.workZ,0),passDepth:finite(value.passDepth,1),feed:finite(value.feed,defaults.feed),travel:finite(value.travel,defaults.travel)}};
export const loadProfiles=():MachineProfile[]=>{try{const parsed:unknown=JSON.parse(localStorage.getItem('i2g-profiles')||'[]');if(!Array.isArray(parsed))return profiles;const builtInIds=new Set(profiles.map(profile=>profile.id));const seen=new Set(builtInIds);const custom:MachineProfile[]=[];for(const value of parsed){const profile=safeProfile(value);if(profile&&!seen.has(profile.id)){seen.add(profile.id);custom.push(profile)}}return[...profiles,...custom]}catch{return profiles}};
export function validate(s:Settings){const w:string[]=[];const numeric=[s.workWidth,s.workHeight,s.outputWidth,s.outputHeight,s.offsetX,s.offsetY,s.rotationDeg,s.feed,s.travel,s.safeZ,s.workZ,s.maxDepth,s.passes,s.lineSpacing,s.precision,s.threshold,s.simplify,s.toolpathDetail];if(numeric.some(value=>!Number.isFinite(value)))w.push('Configuration contains a malformed numeric value.'); if(s.workWidth<=0||s.workHeight<=0||s.outputWidth<=0||s.outputHeight<=0)w.push('Dimensions must be greater than zero.'); if(s.feed<=0||s.travel<=0)w.push('Feed rates must be positive.'); if(s.safeZ<0)w.push('Safe Z should not be negative.'); if(s.workZ>s.safeZ||s.maxDepth>s.safeZ)w.push('Working Z values must be below safe Z.'); if(s.passes<1||!Number.isInteger(s.passes))w.push('Pass count must be a positive integer.'); if(s.lineSpacing<=0)w.push('Line spacing must be positive.'); if(s.toolpathDetail<.05||s.toolpathDetail>5)w.push('Toolpath detail must be between 0.05 mm and 5 mm.'); if(s.precision<0||s.precision>8||!Number.isInteger(s.precision))w.push('Precision must be an integer from 0 to 8.'); const bounds=transformedBounds(s);if(bounds.minX<0||bounds.minY<0||bounds.maxX>s.workWidth||bounds.maxY>s.workHeight)w.push('Transformed image exceeds the configured work area.'); return w;}
